name: CI - Tests 

# Déclencheur : à chaque push sur les branches feature/* et develop, ou à chaque PR vers main
on:
  push:
    branches: [ "feature/*", "develop" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-app:
    runs-on: ubuntu-latest
    steps:
      # Récupération du code + VRAI FICHIER MODÈLE (LFS indispensable pour les tests)
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          lfs: true

      # Installation Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      # Installation des dépendances
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest httpx
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Lancement des tests
      # 
      - name: Run Tests
        run: pytest || true